package com.elka.heofficeclub.other

enum class Action {
  REMOVE,
  ADD,
  GO_NEXT,
  RESTART,
  ORGANIZATION_UPDATED,
  ADDED_NEW_DIVISION_TO_ORGANIZATION,
  REMOVED_DIVISION,
  EDITOR_ADDED,
  GO_ORGANIZATION,
  GO_LOGIN,
  LOAD_PROFILE,
  REMOVED_POSITION,
  CREATE_FILE,
  GO_BACK
}