package com.elka.heofficeclub.other

import com.elka.heofficeclub.R

data class FieldError(val field: Field, var errorType: FieldErrorType?)

enum class FieldErrorType(val messageRes: Int) {
  IS_REQUIRE(R.string.is_require), IS_NOT_EMAIL(R.string.is_no_email), SHORT(R.string.short_error),
  EMAILS_OF_HEADS_IS_EQUAL(R.string.email_of_heads_is_equal),
  EMPTY_ANY_VACATION(R.string.empty_any_vacation),
}

enum class Field {
  EMAIL, PASSWORD, FULL_NAME, SHORT_NAME, CITY,
  STREET, HOUSE, BUILDING, POSTCODE, NAME_OF_ORGANIZATION_HEAD,
  NAME_OF_HUMAN_RESOURCES_DEPARTMENT_HEAD,
  EMAIL_HRD,
  PASSWORD_HRD,
  SALARY,
  NAME,
  CONTRACT_NUMBER,
  CONTRACT_DATE,
  START_WORK_DATE,
  OKPO,
  INN,
  EMPLOYER_FULL_NAME,
  SNILS,
  EMPLOYER_BIRTHDATE,
  EMPLOYER_BIRTHPLACE,
  EMPLOYER_BIRTHPLACE_CODE,
  EMPLOYER_PHONE_NUMBER,
  EMPLOYER_ADDR_BY_PASS,
  EMPLOYER_ADDR_BY_PASS_POSTCODE,
  EMPLOYER_ADDR_BY_FACT,
  EMPLOYER_ADDR_BY_FACT_POSTCODE,
  EMPLOYER_PASS_DATE,
  EMPLOYER_DATE_OF_REG_ADDR,
  EMPLOYER_PASS_SERIAL,
  EMPLOYER_PASS_ORG,
  EMPLOYER_PASS_NUMBER,
  WORK_INTERVAL,
  VACATION_INTERVAL,
  VACATION_B_DESCRIPTION,
  GIFT_DESCRIPTION,
  GIFT_TYPE,
  GIFT_REASON

}