package com.elka.heofficeclub.other

enum class FieldType(val fieldName: String) {
  ORG_NAME("company_name"),
  CODE_OKPO("code_okpo"),
  DOC_NUMBER("doc_number"),
  DOC_CREATED("doc_created"),
  EMPLOYER_FULL_NAME("fill_name"),
  EMPLOYER_TABLE_NUMBER("table_number"),
  DIVISION("division"),
  JOB_ROLE("job_role"),
  CONDITION_OF_WORK("condition_of_work"),
  SALARY_RUB("salary_rub"),
  SALARY_CENT("salary_cent"),
  PREM_RUB("prem_rub"),
  PREM_CENT("prem_cent"),
  TRIAL_PERIOD("trial_period"),
  CONTRACT_DAY("contract_day"),
  CONTRACT_MONTH("contract_month"),
  CONTRACT_YEAR("contract_year"),
  T1_START_WORK("start_work"),
  T1_TO_WORK("to_work"),
  CONTRACT_NUMBER("contract_number"),
  NATURE_OF_WORK("nature_of_work"),
  DATE("date"),
}