package com.elka.heofficeclub.other

enum class Work {
  CREATE_ORGANIZATION,
  LOGIN,
  LOAD_PROFILE,
  LOAD_ORGANIZATION,
  LOGOUT,
  SAVE_CHANGES,
  ADD_DIVISION,
  LOAD_DIVISIONS,
  REMOVE_DIVISION,
  REGISTRATION_EDITOR,
  REMOVE_EDITOR,
  LOAD_EDITOR,
}