package com.elka.heofficeclub.other.documents

enum class DateType {
  CONTRACT,
  START_WORK,
  END_WORK,
  BIRTDAY,
  PASSPORT_DATE,
  REG_ACCORINING_ADDRESS,
  WORK_INTERVAL_START,
  WORK_INTERVAL_END,
  VACATION_A_START,
  VACATION_A_END,
  VACATION_B_START,
  VACATION_B_END
}